AurelicButter/Myneworm

src/app/about-page/about-page.component.ts, src/app/book-page/book-page.component.ts, src/app/contact-page/contact-page.component.ts, src/app/data-correction-form/data-correction-form.component.ts, src/app/faq-page/faq-page.component.ts, src/app/home-page/home-page.component.ts, src/app/imprint-index/imprint-index.component.ts, src/app/imprint-page/imprint-page.component.ts, src/app/missing-page/missing-page.component.ts, src/app/services/metadata.service.spec.ts, src/app/services/metadata.service.ts, src/index.html
Adds more meta tags with focus in Open Graph for link previews to have dynamic data instead of a generic title and description. 
Created a metadata service to manage all of the Open Graph tags as well as the regular meta tags and the title. Then, updated all of the current components to utilize the new service and removed the title service from them.
Internal#741
=> [Feature/741] Added a Metadata Service to Handle Open Graph Link Previews

src/app/book-page/book-page.component.ts, src/app/imprint-page/imprint-page.component.ts, src/app/services/utilities.service.ts
Added an error catch function to the book and imprint page and a utility function to handle errors. If there is a 404 status, the pages will redirect to the 404 page while more unknown errors will error out in the console for support purposes.
Updated the utility service with an API error catching function and then updated the book and imprint page components to use the new function with pipe.
Internal#743
=> [Fix/743] Added Error Redirect for 404 Data Error

src/app/app-routing.module.ts, src/app/app.module.ts, src/app/search-bar/search-bar.component.html, src/app/search-bar/search-bar.component.ts, src/app/search-page/search-page.component.css, src/app/search-page/search-page.component.html, src/app/search-page/search-page.component.spec.ts, src/app/search-page/search-page.component.ts, src/app/search-page/search-page.module.ts, src/app/services/myneworm-api.service.ts
Added a search page for users to see more results and use pages to flip through multiple batches of results.
Created a search page component and set up the router to access the new component at `/search`. The component was designed and the basic functionality was implemented with term searching and pages. Users can also navigate to a specific results using query parameters (ie: `/search?term=Bookworm&page=2`).
A section for advanced options was laid out but not implemented at this time. A new ticket will be made for that as the API needs some more work on search before it can be built.
The search bar was also updated to direct to the search page on submit and show the results page on load.
Internal#721
=> [Feature/721] Added Search Page

src/app/services/metadata.service.ts, src/index.html
Fixes the link previews as the Open Graph meta tags were using a name key and not a property key.
Updated both the main HTML and the metadata service to use property keys.
Internal#754
=> [Fix/754] Fixed OG Meta Tags From Name to Property Key

src/app/privacy-page/privacy-page.component.ts
It adds the meta tag data to the privacy-page.
It was done by importing the Meta service and then injecting it to the component using the updateMetaTags function.
Task #787 from Myneworm Kanban board
=> fix(privacy-page): metadata

src/app/home-page/home-page.component.ts, src/app/imprint-page/imprint-page.component.ts, src/app/shared/calendar-styles.css
Fixes a styling issue where the imprint would not fit in the schedule tag if it was longer than a particular amount of characters.
Updated the format and type schedule tags on the calendars to use a `.format-tag` and a `.type-tag` respectively to maintain the CSS width. Then updated the original `.schedule-tag` width value to fit the larger imprint names.
Internal#766
=> [Fix/766] Added New Classes to Schedule Tags and Updated CSS

src/app/app.component.css, src/app/app.component.html, src/app/search-bar/search-bar.component.css
Updated the navigation bar so it can handle dropdown menus like the search results. 
Also fixed an accessibility issue where the li elements were not direct children of the ul element.
For the search bar elements, the CSS was updated to use a fixed position instead of an absolute position and added a z-index to the bar itself.
With the accessibility issue, I updated the HTML template to swap the li and a tags, then made them use `display: inline-block` which achieved the same results as before.
Also, updated the padding on the logo element in the navigation bar to calculate the padding it should use with clamp. While there is no visible benefit for viewports < 1200px at the moment, the nav bar now is able to show up to the about link instead of the contact link.
Internal#797
=> [Feature/797] Updated Navigation Bar CSS to Handle Dropdown Menus

src/app/app-routing.module.ts, src/app/app.module.ts, src/app/user-nav-menu/user-nav-menu.component.html, src/app/user-settings-page/user-settings-page.component.css, src/app/user-settings-page/user-settings-page.component.html, src/app/user-settings-page/user-settings-page.component.spec.ts, src/app/user-settings-page/user-settings-page.component.ts
Create a user settings page (found at `/settings`) so users can update and delete their accounts as needed by themselves.
Created a component and designed the page layout. Back-end work and API requests will follow in an additional ticket.
Internal#808
=> [Feature/808] Create a User Settings Page

src/app/search-bar/search-bar.component.css
Fixes the search bar positioning when scrolling down pages. The search bar will now remain within the navigation bar.
Updated the CSS styling from `fixed` to `absolute`.
Internal#818
=> [Fix/818] Fixed Search Bar Scrolling with User

src/app/app-routing.module.ts
Updating routing to allow for lazy loading of static page components like the privacy and FAQ pages.
Updated routing to use loadChildren and load components in when needed. Only the pages with loadChildren will not be loaded initially when accessing the site.
Internal#826
=> [Feature/826] Added Lazy Load Functionality to Static Component Pages

src/app/book-page/book-page.component.html
Adds additional template logic to display a `Release: Unknown` on the page if the book does not have a release date yet.
Added another p tag with an ngIf to display the Unknown if release date is null.
Internal#831
=> [Fix/831] Added Default Value if Release Date is Null

src/app/app.component.css, src/app/app.component.html, src/app/home-page/home-page.component.html, src/app/home-page/home-page.component.ts, src/app/shared/navigation-bar.css
Navigation bar is now responsive from ~1390px down to 1000px.
Also improved padding issues as both ends of the navigation bar got extra padding in the Bootstrap addition when they both shouldn't have.
Additionally, the search bar will be replaced with a link to the search page on widths smaller than 1350px
Updated CSS rules to reduce and fix padding in certain spots while also fixing an issue with flexboxes wrapping.
For the search bar, added new rule to display a link instead when the width is less than 1350px.
Internal#834
=> [Fix/834] Improved Navigation Bar to Fit Laptop-sized Widths

src/app/user-profile-page/user-profile-page.component.html
Prevents the location section of the user profile to be displayed if there is no location value to display.
Added an ngIf to the p tag for the location section.
Internal#842
=> [Fix/842] Added Check To Not Display Location if Value is Null

src/app/book-page/book-page.component.html, src/app/book-page/book-page.component.ts, src/app/models/AssetSize.ts, src/app/search-bar/search-bar.component.html, src/app/search-bar/search-bar.component.ts, src/app/search-page/search-page.component.html, src/app/search-page/search-page.component.ts, src/app/services/myneworm-api.service.ts, src/app/user-list-page/table-display/table-display.component.html, src/app/user-list-page/table-display/table-display.component.ts, src/app/user-list-page/user-list-page.component.ts
Images will now request based on size of need instead of the original file on the API server. This leads to less data being requested overall and might speed up requests depending on connection speed and amount of data.
Added a new function to the Myneworm-API service to allow size input for the link. Then, went around the codebase updating existing cover links to use the new function.
Internal#812
=> [Feature/812] Updated Images to Use New Size Routing

src/app/login-page/login-page.component.css, src/app/login-page/login-page.component.html, src/app/login-page/login-page.component.ts, src/app/registration-page/registration-page.component.html, src/app/registration-page/registration-page.component.ts
Updated Login and Registration Pages with Toast Notifications.
Using the existing ToastService, moved all errors and success messages for those respective pages to trigger toast notifications instead. Then, removed any existing general notification area for the components.
Internal#840
=> [Feature/840] Updated Login and Registration Page with Toast Notifications

src/app/user-settings-page/user-settings-page.component.ts
Updates the backend logic for the user settings page to use null values instead of empty strings as this causes issues with the API and does not clear the selected values back to null.
Added checks to the data body to see if the input is an empty string or not. If so, use null instead.
Internal#866
=> [Fix/866] Updated Settings Page to Use Null Values Instead of Empty Strings

src/app/app.component.css, src/app/app.component.html, src/app/shared/list-entry-modal/list-entry-modal.component.css, src/app/shared/list-entry-modal/list-entry-modal.component.html
Updates the styles to accommodate for larger resolutions in the ListEntryModal. Also updated the main site to fix the margin-top for the page contents.
Updated the ListEntryModal styles to be more flexible for heights and removed various properties that cause image squish or hard to read text at resolutions >1440px.
For the margin-top, the router-outlet was wrapped in a parent div and that div was styled with the `margin-top` property.
Internal#862 & Internal#869
=> [Fix/862 & Fix/869] Updated Styles to Accommodate Larger Resolutions + Fix Margins

src/app/services/authentication/authentication.service.ts
Updates the authentication service to use the "Username or password is invalid" message instead of doing a 401 unauthorized error on login.
Added a check in the catchError function to look for 401 errors and then return a static string instead.
Internal#876
=> [Fix/876] Updated Error Message For Login Credentials If Invalid

src/app/book-page/book-page.component.html
Fixes check on the book page to display the message "No description available" if the value is null instead of ''.
Added checks for null values and boolean operators to make sure only one p tag is shown on the page.
Internal#886
=> [Fix/886] Fixed Check to Show Description Backup on Book Page

src/app/book-page/book-page.component.html, src/app/book-page/book-page.component.ts, src/app/shared/list-entry-modal/list-entry-modal.component.ts
The button now switches between 'Add to List' and 'Update List' depending on if the authenticated user has a list entry for the target book or not.
Updated the book page component with a new boolean variable to keep track if the user has a list entry or not. Also updated the ListEntryModal to return data if the entry was deleted or not. The boolean variable on book page will update when the dialog is closed.
Internal#878
=> [Feature/878] Updated Entry Button on Book Page to Display Add or Update

src/app/app.module.ts, src/app/services/myneworm-api.service.ts, src/app/user-settings-page/delete-confirmation/delete-confirmation.component.css, src/app/user-settings-page/delete-confirmation/delete-confirmation.component.html, src/app/user-settings-page/delete-confirmation/delete-confirmation.component.spec.ts, src/app/user-settings-page/delete-confirmation/delete-confirmation.component.ts, src/app/user-settings-page/user-settings-page.component.html, src/app/user-settings-page/user-settings-page.component.ts
Users can now delete their accounts on demand by clicking the delete button in their settings.
Updated the delete button area on the page to list exactly what to expect during the deletion process. Then implemented the button to open a dialog menu to force users to confirm their choice as well as reinforce what will happen with the account and the process. On confirmation, the user is logged out of the account and redirected back to the home page.
Internal#850
=> [Feature/850] Added Functionality to Delete Button

src/app/app.module.ts, src/app/user-profile-page/statistic-display/statistic-display.component.ts, src/app/user-profile-page/user-profile-page.component.html, src/app/user-profile-page/user-profile-page.component.ts
Fixed an issue where the profile statistics display was not being displayed on a user's profile.
Added an extra input to the statistic displays so that the page can trigger updated when needed. Since the display implements OnChange, the boolean update will cause the display to reload with the appropriate data.
Internal#860
=> [Fix/860] Fixed Profile Statistics Display From Not Show Statistics

src/app/models/toastNotification.ts, src/app/services/toast.service.ts, src/app/shared/toast-messages/toast-messages.component.ts
Updates the toast notifications to auto dismiss themselves after a certain period of time instead of needing manual dismissal.
Added a setTimeout function to fire after a few seconds depending on message length. At a minimum, the message will be displayed for about 7 seconds.
Internal#870
=> [Feature/870] Added Timeout To Auto Dismiss Toast Notifications

src/app/search-page/search-page.component.html, src/app/search-page/search-page.component.ts, src/app/user-list-page/table-display/table-display.component.html
Added previous and next page buttons to the bottom of the search results on the search page. They function exactly like the ones on the top of the search results. Updated said buttons from a tags into button tags to help with accessibility and functionality.
Images on the search page and user list pages now have a lazy load flag to allow for some of the images to be loaded later when the user has a chance to see them.
Copied the buttons and added a new set after the table element on the HTML file. Then, updated them into buttons and verified they still functioned as anticipated locally. 
For the images, added the flag to the img tag and then verified if the images were lazy loaded in the network tab locally.
Internal#887
=> [Feature/887] Added Page Buttons to Bottom of Search Page + Lazy Load Images

src/app/app.component.html, src/app/user-nav-menu/user-nav-menu.component.css, src/app/user-nav-menu/user-nav-menu.component.html, src/app/user-nav-menu/user-nav-menu.component.ts
Added an additional link within the user's navigation menu to let the user immediately click to their own list. Also fixed an issue with hovering for the menu as mobile users are unable to hover.
Added an additional `a` tag to the list of existing links and verified that it did navigated to the authenticated user's list locally.
Added an additional check for `:active` on the menu wrapper class to allow mobile users to click on their username and bring up the navigation menu.
Internal#892 & Internal#895
=> [Feature/892 & Fix/895] Updated User Navigation Menu With Link to User's List + Fixed Mobile Hover Issue

src/app/models/BookFormat.ts, src/app/models/SearchOptions.ts, src/app/search-page/search-page.component.css, src/app/search-page/search-page.component.html, src/app/search-page/search-page.component.ts, src/app/services/myneworm-api.service.ts
Implements the advanced filters options on the search page as well as add indicators if the result table used a term to search with.
Created a new form that appears when the user clicks on the "Show filters" button. On click, the form appears and the user is able to enter in earliest date, latest date, imprint, book type, and book format to filter the search further. 
If the user uses a link with parameters in it, the page will automatically input those values into the filter form and search based on what was defined. The form will also be present when the user loads the page for the first time.
Also update the "No Results" message to include the term it used to search as well as if filters were present in the result.
Internal#753 & Internal#880
=> [Feature/753 & Feature/880] Implemented Advanced Filters for Search Page

src/app/models/ListEntry.ts, src/app/shared/list-entry-modal/list-entry-modal.component.ts
Updates the datepickers in the ListEntryModal to allow for null/undefined values submitted by the user.
Prevents overwrite by backend functions if the date becomes "". Then, on submission, a final check is made and any "" or undefined value is overwritten to null on entry update.
Internal#889
=> [Fix/889] Updated ListEntryModal to Allow for Null Values on Dates

src/app/services/myneworm-api.service.ts
Patches the updateAccount function for the Myneworm-API to encode the password before sending it to the API.
Encoded using Base64 as the service already does for login credentials.
Internal#903
=> [Spike/903] Encoded Password Before Sending to API to Update Account Details

src/app/functions/formatOwnerStatus.ts, src/app/models/ListEntryStatus.ts, src/app/models/userStatisticsData.ts, src/app/user-list-page/table-display/table-display.component.css, src/app/user-list-page/table-display/table-display.component.html, src/app/user-list-page/table-display/table-display.component.ts, src/app/user-list-page/user-list-page.component.html, src/app/user-list-page/user-list-page.component.ts, src/app/user-profile-page/statistic-display/statistic-display.component.css, src/app/user-profile-page/user-profile-page.component.ts
Added `Ordered` ownership status across the site as needed. Also fixed two issues with the user list page and sorting. First, tables are now sorted by titles in ascending order. Second, fixed an issue with sort options not rearranging the entries. 
For the ordered status, updated various enums and conditions around the site where other ownership statuses were used.
For the list page, unified everything in an Angular MatTableDataSource element. Then updated the variable with a custom filter and sort function to handle conditions on the page. Likewise, added various MatSort options into the table display which reenabled various sort mechanics.
Internal#863, Internal#879, & Internal#905
=> [Fix/863, Feature/879, & Fix/905] Added Ordered Status + Updated List Page

src/app/shared/navigation-bar.css
Fixes an issue where the navigation search bar results would hide behind site content and not overlaid on top of the content as intended.
Added a position rule in the CSS file as apart of `nav-list`.
Internal#931
=> [Fix/931] Fixed Navigation Search Results Not Being Overlaid On Top of Content

src/styles.css
Fixes a CSS style issue where not all of the btn-link classed links kept their colour on hover.
Added `!important` to the style property.
Internal#934
=> [Fix/934] Fixed Style Issue Where Footer Contact Link Would Change Colour on Hover

src/app/admin-pages/admin-routing.module.ts, src/app/admin-pages/admin.module.ts, src/app/admin-pages/book-correction-landing/book-correction-landing.component.css, src/app/admin-pages/book-correction-landing/book-correction-landing.component.html, src/app/admin-pages/book-correction-landing/book-correction-landing.component.spec.ts, src/app/admin-pages/book-correction-landing/book-correction-landing.component.ts, src/app/admin-pages/book-correction/book-correction.component.html, src/app/admin-pages/book-correction/book-correction.component.spec.ts, src/app/admin-pages/book-correction/book-correction.component.ts, src/app/admin-pages/landing/landing.component.css, src/app/admin-pages/landing/landing.component.html, src/app/models/BookCorrection.ts, src/app/services/myneworm-admin.service.spec.ts, src/app/services/myneworm-admin.service.ts
Creates the pages needed for book correction reviews and designed the layout of the list page.
Designed the table to display various correction submissions for book entries. Each row is clickable and sends the moderator user into a page that will display the details and changes suggested. Routes for these submissions have been changed from `data-correction` to `corrections/book/:isbn/:correctionID` and sets up a similar pathing for series corrections (planned for a separate epic).
Implementation of working interactions (ie: viewing existing entries and filtering) were broken from this ticket and made into two separate tickets to handle the complexity of the task better.
Ticket: Internal#938
Created tickets: Internal#942 & Internal#943
=> [Feature/938] Create Page for Book Corrections in Admin Panel

src/app/shared/list-entry-modal/list-entry-modal.component.css, src/app/shared/list-entry-modal/list-entry-modal.component.html
Adds a cancel button on the top of the ListEntryModal menu to close without saving. Also added a couple of CSS styling rules to improve the modal experience on tablets and mobile devices.
Added an X button to the header of the modal and then styled it as needed. Then, added a click event to trigger the `close()` function.
For styling, I used the brower's devtools to mimic a mobile & tablet width. Then, added styling based on what I was shown until the modal looked slightly better than the previous version.
Internal#867
=> [Feature/867] Added Cancel Button & Update Styling on ListEntryModal

src/app/pages/faq/faq.component.css, src/app/pages/faq/faq.component.html, src/app/pages/faq/faqData.ts
Updates the styling on the FAQ page to match the styling used in the support page.
Referred to the support page to identify which styling rules to apply to the FAQ page. Then, added a div wrapper to apply the width and removed some redundant styling with the headers to create a matching style layout.
Internal#939
=> [Feature/939] Updated Styling to Match Support Page for FAQ Page

src/app/functions/formatDateString.ts
Fixes a display issue where the start and end date months would be off by one in the list entries.
The issue was related to the native `getMonth` function where it returns 0-11. Updated the `formatDateString` function to add one to `getMonth` to return a 1-12 range.
Internal#945
=> [Fix/945] Fixed Display Issue on Start & End Dates for List Entries

src/app/user-pages/profile/profile.component.css
Fixes an issue where the bottom border did not extend the full length of the screen width on Firefox browsers.
Updated the width property from `-webkit-fill-availible` to `100%`.
Internal#955
=> [Fix/955] Fixed Border Styling For User Profiles on Firefox Browsers

src/app/search-bar/search-bar.component.html
Fixes an issue with the search bar where certain titles would not appear in the dropdown.
Updated the if statements around truncating the title as there was a condition for any title above 57 characters and any title below 57 characters. The titles used as examples for replication were all exactly 57 characters and thus did not meet any if condition. Now if the title is exactly 57 characters long, the title will appear as if the title had less than 57 characters.
Internal#936
=> [Fix/936] Fixed Issue with Disappearing Titles

src/app/admin-pages/book-correction/book-correction.component.css, src/app/admin-pages/book-correction/book-correction.component.html, src/app/admin-pages/book-correction/book-correction.component.ts, src/app/models/BookCorrection.ts
Fixed an issue where the new release dates were not displayed on the correction form to the approver for verification.
This was a graphical issue so no back-end updates required.
The fix now sets the default value of the input field with a formatted `YYYY-MM-DD` string instead of attempting to infer it from ngModel.
Internal#961
=> [Fix/961] Fixed Issue With New Release Dates Not Displaying on Correction Form

src/app/pages/book-correction-form/book-correction-form.component.ts
Fixed an issue where the cover URL was not being saved on correction submission.
Updated the key from cover_url to cover_image per API changes and requirements.
Internal#960
=> [Fix/960] Updated Key in Book Correction Submission
