package-lock.json
package.json
src/app/services/metadata.service.ts
src/index.html

Hotfixing the Open Graph link previews for a wrong key.
See individual PRs for how tos.
Related PRs: #53 
Closes ticket Internal#754

Beta Release 0.6.1

---

src/app/shared/datepicker-modal/datepicker-modal.component.css
src/app/shared/datepicker-modal/datepicker-modal.component.html
src/app/shared/datepicker-modal/datepicker-modal.component.ts

Added a date validator to check if the date has a 4 digit year, 2 digit month, and 2 digit day. If the date is invalid, the selected date will not update and output an error message.
Updated the DatePicker modal with a function and additional logic to verify a valid date before parsing and updating the current calendar date.
Internal#760

[Fix/760] Fixed DatePicker Date Picking Issue

---

src/app/services/utilities.service.ts
src/app/shared/datepicker-modal/datepicker-modal.component.ts

Fixed the DatePicker to prevent the picker from updating the date if the user clicks on the cancel button.
Updated the close function in the DatePicker with a return keyword as the defensive condition was missing the key and continuing as if the button was a submit button.
Internal#765
Also removed a stray dash in the APIDateFormatter utility function as there was one after the date value.

[Fix/765] Fixed DatePicker Changing Dates on Cancel

---

src/app/shared/datepicker-modal/datepicker-modal.component.ts

Fixes a display issue with the date in DatePicker.
Fixed a bug where the offset would add an extra day so dates like December 31st, 2019 would become January 1st, 2020.
Internal#777

[Fix/777] Fixed Display Issue with Dates in DatePicker

---

src/app/app-routing.module.ts
src/app/app.module.ts
src/app/database-guidelines/database-guidelines.component.css
src/app/database-guidelines/database-guidelines.component.html
src/app/database-guidelines/database-guidelines.component.spec.ts
src/app/database-guidelines/database-guidelines.component.ts
src/app/faq-page/faqData.ts

Added a page for database guidelines for people to refer to when adding or updating entries on the site.
Created a new component and added content for the page. Updated the router so the new page can be found at `/guidelines` and the FAQ was updated to include a link to the page.
Internal#793

[Feature/793] Added Database Guidelines Page

---

angular.json
package-lock.json
package.json
src/app/app-routing.module.ts
src/app/app.component.css
src/app/app.component.html
src/app/app.component.ts
src/app/app.module.ts
src/app/login-page/login-page.component.css
src/app/login-page/login-page.component.html
src/app/login-page/login-page.component.spec.ts
src/app/login-page/login-page.component.ts
src/app/models/authInterfaces.ts
src/app/models/loginForm.ts
src/app/services/authentication/authentication.guard.spec.ts
src/app/services/authentication/authentication.guard.ts
src/app/services/authentication/authentication.service.spec.ts
src/app/services/authentication/authentication.service.ts
src/app/services/authentication/local-cookies.service.spec.ts
src/app/services/authentication/local-cookies.service.ts
src/app/shared/navigation-bar.css
src/app/user-nav-menu/user-nav-menu.component.css
src/app/user-nav-menu/user-nav-menu.component.html
src/app/user-nav-menu/user-nav-menu.component.spec.ts
src/app/user-nav-menu/user-nav-menu.component.ts
src/environments/environment.ts
src/proxy.conf.json
tsconfig.app.json

Creates a login page for the site. 
Updated the navigation bar to contain a login button for non-authenticated sessions and a user menu for authenticated sessions. The menu also contained a function for logging out.
Also updates local configuration to proxy to a local API rather than both local and testing proxying to the development API.
Started by creating the initial login page with buttons for login, password loss, and registration. Only login was implemented for the ticket. Then, created two services and a guard to handle authentication and user data via local cookies.
Updated the navigation bar so the login/user menu can be on the bar to the right of the search bar. Updated the CSS styling so everything could function as before and improved the responsiveness of it by 100 pixels. …

[Feature/782 & Feature/806] Created Login Page

---

src/app/app-routing.module.ts
src/app/app.module.ts
src/app/functions/formatDateString.ts
src/app/functions/formatOwnerStatus.ts
src/app/models/ListEntry.ts
src/app/models/userData.ts
src/app/services/myneworm-api.service.ts
src/app/user-list-page/table-display/table-display.component.css
src/app/user-list-page/table-display/table-display.component.html
src/app/user-list-page/table-display/table-display.component.spec.ts
src/app/user-list-page/table-display/table-display.component.ts
src/app/user-list-page/user-list-page.component.css
src/app/user-list-page/user-list-page.component.html
src/app/user-list-page/user-list-page.component.spec.ts
src/app/user-list-page/user-list-page.component.ts
src/app/user-list-page/user-list-page.module.ts
src/styles.css

Creates a user list page (found at `user/:username/lists`) to show what the user has added to their own lists. Includes API call to grab their entries, filters to sort by activity status, ownership, and book type, ability to ascend or descend entries by title, score, or reread count, and an additional dropdown to display when they started reading, finished reading, and their notes for the entry. 
Created the initial user-list-page component and designed the general layout with CSS. Then, updated the table to allow sorting entries by title, score, or reread count. After, broke the component into two with table-display handling the status tables and the user-list-page component managing the overall view. 
Continued by adding inputs into table-display for the remaining filters and additional …

[Feature/828] Added User List Page

---

src/app/app-routing.module.ts
src/app/app.module.ts
src/app/models/userData.ts
src/app/models/userStatisticsData.ts
src/app/services/myneworm-api.service.ts
src/app/user-list-page/user-list-page.component.css
src/app/user-list-page/user-list-page.component.html
src/app/user-nav-menu/user-nav-menu.component.html
src/app/user-profile-page/statistic-display/statistic-display.component.css
src/app/user-profile-page/statistic-display/statistic-display.component.html
src/app/user-profile-page/statistic-display/statistic-display.component.spec.ts
src/app/user-profile-page/statistic-display/statistic-display.component.ts
src/app/user-profile-page/user-profile-page.component.css
src/app/user-profile-page/user-profile-page.component.html
src/app/user-profile-page/user-profile-page.component.spec.ts
src/app/user-profile-page/user-profile-page.component.ts

Creates a user profile page to showcase a little bit about the user and their list statistics.
Also updates the list page to include a link back to the profile at the top of the header.
Updated the navigation bar to include a link to the user's profile if authenticated. Then, added routes into the router so that `/user/:username` and `/user/:username/profile` both direct to the page. Designed and stylized the page to look and feel like a profile. Then, tested it with fake data through a local version of the API to make sure it would be able to get data and display it properly.
Created a link tag for the profile link in the header of the list page and then stylized it to blend in with the rest of the title.
Internal#809
These changes will need the next version of the Myneworm-API to run …

[Feature/809] Create a User Profile Page

---

src/app/app-routing.module.ts
src/app/app.module.ts
src/app/login-page/login-page.component.css
src/app/login-page/login-page.component.html
src/app/models/RegistrationData.ts
src/app/registration-page/registration-page.component.css
src/app/registration-page/registration-page.component.html
src/app/registration-page/registration-page.component.spec.ts
src/app/registration-page/registration-page.component.ts
src/app/services/myneworm-api.service.ts

Creates the registration page for users to sign up at.
Updated the routing to place the new page at `/register`. Then, created the form to grab all of the user details needed like username, password, and date of birth. Styled it to look nicer and did a bit of responsive styling so it can work all the way down to a small mobile. 
Also updated the register button on the login page to direct to the registration form.
Updated Myneworm-API service to include a function to send the user information to the API and create the account.
Internal#804

[Feature/804] Created Registration Page

---

src/app/app.component.css
src/app/app.component.html
src/app/app.module.ts
src/app/models/accountUpdateData.ts
src/app/models/profileUpdateData.ts
src/app/models/userData.ts
src/app/services/myneworm-api.service.ts
src/app/services/toast.service.spec.ts
src/app/services/toast.service.ts
src/app/shared/shared.module.ts
src/app/shared/toast-messages/toast-messages.component.css
src/app/shared/toast-messages/toast-messages.component.html
src/app/shared/toast-messages/toast-messages.component.spec.ts
src/app/shared/toast-messages/toast-messages.component.ts
src/app/user-profile-page/user-profile-page.component.css
src/app/user-profile-page/user-profile-page.component.ts
src/app/user-settings-page/user-settings-page.component.css
src/app/user-settings-page/user-settings-page.component.html
src/app/user-settings-page/user-settings-page.component.ts

Adds functionality to the user settings page as well as fix a couple of minor bugs for the user profile page.
Updated the Myneworm-API service to grab both profile and account data. Then, updated the form to use Bootstrap elements and link form values to component variables.
Created a ToastNotification system where components can send messages to display to the user. The user settings page is the only page using it at the moment.
Added a `overflow-wrap: anywhere` to both the user profile header and user profile about me section as if given a long enough string, it will overflow outside of the browser width.
Updated the last online display value to use the input from Moment.js instead of switch statements (which were also broken as it displayed a day old login [ie: Yesterday] as a week …

[Feature/823, Fix/846, Fix/849] Added Functionality to User Settings Page

---

src/app/app.component.css
src/app/app.component.html
src/app/app.component.ts
src/app/shared/toast-messages/toast-messages.component.css
src/app/user-profile-page/statistic-display/statistic-display.component.css
src/app/user-profile-page/statistic-display/statistic-display.component.html
src/app/user-profile-page/statistic-display/statistic-display.component.ts
src/styles.css

Updated Profile Page so that the statistic bars for profiles are curved on either end, regardless of which values are present.
Updated page styles to prevent toast notifications from shifting page contents down when notifications are present.
Buttons now change colour on hover.
For the profile page fix, the main container for the bars now have an `overflow: hidden` and border radiuses. The original first-child and last-child selector rules were removed.
For the toast notifications, wrapping the notification component into another div and setting that as the sticky one fixed every known issue with the toast styling. Only had to add an additional rule for the routed divs to include margin space on the top to be in the same position as before.
Also updated the global style so that buttons …

[Fix/856 & Fix/857] Fixed Style Issues For Profile Page and Toast Notifications

---

src/app/book-page/book-page.component.css
src/app/book-page/book-page.component.html
src/app/shared/list-entry-modal/list-entry-modal.component.css
src/app/shared/list-entry-modal/list-entry-modal.component.html
src/app/shared/list-entry-modal/list-entry-modal.component.ts

Fixes for several items:
- Buttons on the book page now shift into columns for laptop-sized or smaller resolutions
- Fixed aria-disabled attributes for buttons
- Fixed date shifting for manual input dates in ListEntryModal
- Fixed scrolling on ListEntryModal
- Added placeholder with date format for ListEntryModal datepickers
For the buttons on the book page, updating the flex-direction from row to column works perfectly. Also added an extra rule to add a margin-top to n+2 child buttons to give extra space on the page.
For the ListEntryModal, validateDate no longer goes through the API Date Formatter and keeps its original value (thus removing the date shift from the `new Date()` function). 
In the template aspect of the modal and page, styles and additional properties were defined and …

[Fix/865, Fix/881, Fix/884, Fix/855] Update Styles for Book Page and ListEntryModal

---

src/app/models/validationPatterns.ts
src/app/services/authentication/authentication.service.ts
src/app/user-settings-page/user-settings-page.component.html
src/app/user-settings-page/user-settings-page.component.ts

Adds a button to clear all authenticated sessions for the given account in the user settings page.
Implemented the function to hit the clear endpoint in the authentication service. Then relayed that functionality through the component and onto a click action for the button.
Internal#874

[Feature/874] Implemented Clear Sessions Button

---

src/app/admin-pages/admin-routing.module.ts
src/app/admin-pages/admin.module.ts
src/app/admin-pages/data-correction/data-correction.component.html
src/app/admin-pages/data-correction/data-correction.component.spec.ts
src/app/admin-pages/data-correction/data-correction.component.ts
src/app/admin-pages/home-panel/home-panel.component.css
src/app/admin-pages/home-panel/home-panel.component.html
src/app/admin-pages/home-panel/home-panel.component.spec.ts
src/app/admin-pages/home-panel/home-panel.component.ts
src/app/admin-pages/landing/landing.component.css
src/app/admin-pages/landing/landing.component.html
src/app/admin-pages/landing/landing.component.spec.ts
src/app/admin-pages/landing/landing.component.ts
src/app/admin-pages/user-management/user-management.component.html
src/app/admin-pages/user-management/user-management.component.spec.ts
src/app/admin-pages/user-management/user-management.component.ts
src/app/admin-pages/user-report/user-report.component.html
src/app/admin-pages/user-report/user-report.component.spec.ts
src/app/admin-pages/user-report/user-report.component.ts
src/app/app-routing.module.ts
src/app/services/authentication/authentication.service.ts
src/app/services/authentication/is-moderator.guard.spec.ts
src/app/services/authentication/is-moderator.guard.ts
src/app/user-nav-menu/user-nav-menu.component.html
src/app/user-nav-menu/user-nav-menu.component.ts

Creates the admin dashboard where moderators and admins can work out of for Myneworm-related content and needs.
Designed the initial dashboard/landing page in a module which is lazy-loaded on request. Also updated the user navigation menu to include a link to the admin portal if the user is a moderator or admin.
Internal#893

[Feature/893] Create Admin Portal for Moderators and Admins

---

JenkinsFile
package-lock.json
package.json
src/app/services/authentication/authentication.service.ts
src/app/services/myneworm-api.service.ts
src/app/user-pages/profile/profile.component.ts
src/app/user-pages/user-list/user-list.component.ts
src/app/user-pages/wishlist/wishlist.component.ts
src/app/user-settings-page/delete-confirmation/delete-confirmation.component.ts
src/app/user-settings-page/user-settings-page.component.ts

Reviewed and corrected error checking for user settings as there were reports of error messages on successful updates to user accounts.
Verified how the errors were interacting in the catch within each call. Then, if I found a discrepancy, I either updated the error message to match what was actually happening or added additional checks to give a more consistent message. 
Also moved all of the user API errors to be handled within the initial service functions to reduce complexity and LOC.
Internal#923

[Fix/923] Reviewed Error Checking for User Settings Page

---

.github/CONTRIBUTING.md
.github/workflows/eslint.yml
README.md
src/proxy.conf.json

Updates the README and CONTRIBUTING files for more accurate and clearer information.
Updated text information within the given files.
Internal#940

[Manage/940] Updated README and CONTRIBUTING For More Accurate Information

---

src/app/imprint-page/imprint-page.component.css

Updates the imprint page styling to fix an issue with imprint logos appearing in the same row as the imprint name.
Updated the flex display from the default direction of row to column. 
Internal#877

[Fix/877] Updated Styling on Imprint Page to Fix Collision Issue

---

src/app/admin-pages/admin.module.ts
src/app/admin-pages/book-correction-landing/book-correction-landing.component.html
src/app/admin-pages/book-correction-landing/book-correction-landing.component.ts
src/app/admin-pages/book-correction/book-correction.component.css
src/app/admin-pages/book-correction/book-correction.component.html
src/app/admin-pages/book-correction/book-correction.component.ts
src/app/admin-pages/book-correction/moderator-input-modal/moderator-input-modal.component.css
src/app/admin-pages/book-correction/moderator-input-modal/moderator-input-modal.component.html
src/app/admin-pages/book-correction/moderator-input-modal/moderator-input-modal.component.spec.ts
src/app/admin-pages/book-correction/moderator-input-modal/moderator-input-modal.component.ts
src/app/pages/book-page/book-page.component.html
src/app/services/myneworm-admin.service.ts
src/app/services/myneworm-api.service.ts

Creates and implements the page for admins and moderators to compare the data correction with the current data in the database. The reviewer can approve or deny the correction based on their judgement.
Created two new components, one for the form display and one for a confirmation modal. At the top of the page, the ISBN number as well as the submitter's username and comments are displayed. If the form is not pending approval, the reviewer's username and comments are also displayed. 
Fields displayed only if the correction form targets them (ie: title won't be displayed if the title is not apart of the corrections). 
Reviewers will have the choice of three buttons at the button. One to go back to the corrections list, one to reject the correction, and one to approve the correction. If …

[Feature/942] Create Book Correction Form Display for Moderators

---

src/app/search-page/search-page.component.ts

Fixes an issue where the search page did not update the website's meta data when loaded without parameters.
Added an `updateMetaData` call in the existing `ngOnInit` function.
Internal#956

[Fix/956] Updated Search Page Component to Update Meta Data

---

JenkinsFile

Fixes incorrect branch name for production builds.

Fix Jenkins Pipeline

---

JenkinsFile

Fixed Extra Stage Trigger in Master Build
